Update workflows

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -31,7 +31,11 @@ jobs:
         id: version-output
         run: |
           if [[ "${{ inputs.version }}" == "latest" || "${{ inputs.version }}" == "" ]]; then
-            VERSION=$(curl  "https://api.github.com/repos/bitwarden/directory-connector/releases" | jq -c '.[] | select(.tag_name) | .tag_name' | head -1 | grep -ohE '20[0-9]{2}\.([1-9]|1[0-2])\.[0-9]+')
+            VERSION=$(curl -sSfL "https://api.github.com/repos/bitwarden/key-connector/releases" | jq -c '.[] | select(.tag_name) | .tag_name' | head -1 | grep -ohE '20[0-9]{2}\.([1-9]|1[0-2])\.[0-9]+')
+            if [[ -z "$VERSION" ]]; then
+              echo "Failed to fetch latest version"
+              exit 1
+            fi
             echo "Latest Released Version: $VERSION"
             echo "version=$VERSION" >> $GITHUB_OUTPUT
           else
@@ -44,8 +48,6 @@ jobs:
     runs-on: ubuntu-24.04
     needs: setup
     env:
-      _AZ_REGISTRY: bitwardenprod.azurecr.io
-      _PROJECT_NAME: key-connector
       _RELEASE_VERSION: ${{ needs.setup.outputs.release-version }}
     permissions:
       id-token: write
@@ -54,71 +56,49 @@ jobs:
       - name: Install Cosign
         uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1
 
-      - name: Log in to Azure
-        uses: bitwarden/gh-actions/azure-login@main
-        with:
-          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
-          client_id: ${{ secrets.AZURE_CLIENT_ID }}
-
-      - name: Log in to ACR
-        run: az acr login -n ${_AZ_REGISTRY%.azurecr.io}
-
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
+        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Pull image
-        run: docker pull $_AZ_REGISTRY/$_PROJECT_NAME:dev
+        run: docker pull ghcr.io/bitwarden/key-connector:dev
 
       - name: Tag version and latest
         run: |
           if [[ "${{ inputs.publish_type }}" == "Dry Run" ]]; then
-            docker tag $_AZ_REGISTRY/$_PROJECT_NAME:dev ghcr.io/bitwarden/$_PROJECT_NAME:dryrun
+            docker tag ghcr.io/bitwarden/key-connector:dev ghcr.io/bitwarden/key-connector:dryrun
           else
-            docker tag $_AZ_REGISTRY/$_PROJECT_NAME:dev $_AZ_REGISTRY/$_PROJECT_NAME:$_RELEASE_VERSION
-            docker tag $_AZ_REGISTRY/$_PROJECT_NAME:dev $_AZ_REGISTRY/$_PROJECT_NAME:latest
-
-            docker tag $_AZ_REGISTRY/$_PROJECT_NAME:dev ghcr.io/bitwarden/$_PROJECT_NAME:$_RELEASE_VERSION
-            docker tag $_AZ_REGISTRY/$_PROJECT_NAME:dev ghcr.io/bitwarden/$_PROJECT_NAME:latest
+            docker tag ghcr.io/bitwarden/key-connector:dev ghcr.io/bitwarden/key-connector:$_RELEASE_VERSION
+            docker tag ghcr.io/bitwarden/key-connector:dev ghcr.io/bitwarden/key-connector:latest
           fi
-
-      - name: Push release version and latest image to ACR
-        if: ${{ inputs.publish_type != 'Dry Run' }}
-        run: |
-          docker push $_AZ_REGISTRY/$_PROJECT_NAME:$_RELEASE_VERSION
-          docker push $_AZ_REGISTRY/$_PROJECT_NAME:latest
 
       - name: Push release version and latest image
         if: ${{ inputs.publish_type != 'Dry Run' }}
         run: |
-          docker push ghcr.io/bitwarden/$_PROJECT_NAME:$_RELEASE_VERSION
-          docker push ghcr.io/bitwarden/$_PROJECT_NAME:latest
+          docker push ghcr.io/bitwarden/key-connector:$_RELEASE_VERSION
+          docker push ghcr.io/bitwarden/key-connector:latest
 
       - name: Sign image with Cosign
+        if: ${{ inputs.publish_type != 'Dry Run' }}
         run: |
-          cosign sign --yes ghcr.io/bitwarden/$_PROJECT_NAME:$_RELEASE_VERSION
-          cosign sign --yes ghcr.io/bitwarden/$_PROJECT_NAME:latest
+          cosign sign --yes ghcr.io/bitwarden/key-connector:$_RELEASE_VERSION
+          cosign sign --yes ghcr.io/bitwarden/key-connector:latest
 
       - name: Verify the signed image with Cosign
+        if: ${{ inputs.publish_type != 'Dry Run' }}
         run: |
           cosign verify \
             --certificate-identity "${{ github.server_url }}/${{ github.workflow_ref }}" \
             --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
-            ghcr.io/bitwarden/$_PROJECT_NAME:$_RELEASE_VERSION
+            ghcr.io/bitwarden/key-connector:$_RELEASE_VERSION
 
           cosign verify \
             --certificate-identity "${{ github.server_url }}/${{ github.workflow_ref }}" \
             --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
-            ghcr.io/bitwarden/$_PROJECT_NAME:latest
+            ghcr.io/bitwarden/key-connector:latest
 
       - name: Log out of Docker
-        run: |
-          docker logout ghcr.io
-          docker logout $_AZ_REGISTRY
-
-      - name: Log out from Azure
-        uses: bitwarden/gh-actions/azure-logout@main
+        run: docker logout ghcr.io
